version: '3.2'

services:
  backend:
    image: ltsiciliano/finances-control
    ports:
      - 40001:40001
    container_name: finances-control-backend
    restart: always
    networks:
      - finances
  front:
    image: ltsiciliano/finances-control-front
    ports:
      - 8080:80
    container_name: finances-control-front
    restart: always
    depends_on:
      - backend
    networks:
      - finances
  domain:
    image: ltsiciliano/finances-control-domain
    ports:
      - 50001:50001
    container_name: finances-control-domain
    restart: always
    networks:
      - finances
networks:
  finances: {}
